apiVersion: apps/v1
kind: Deployment
metadata:
  name: weathervane
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: weathervane
        image: weathervane-0-0-3
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: weathervane
  namespace: default
spec:
  selector:
    bb: web
  ports:
  - port: 5000
    targetPort: 5000