name: AWS ECR
  # You may pin to the exact commit or the version.
  # uses: kciter/aws-ecr-action@79255b7c5aa03dbf6d7c46cff2bfd049874cd98d
  jobs:
    build-and-push:
      runs-on: ubuntu-latest
      steps:
      - uses: kciter/aws-ecr-action@v4
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID}}
        with:
          # The AWS access key id
          access_key_id: $AWS_ACCESS_KEY
          # The AWS secret access key
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          # AWS Account ID
          account_id: $AWS_ACCOUNT_ID
          # Name of your ECR repository
          repo: weathervane
          # The AWS region
          region: us-east-2
          # Set this to true to create the repository if it does not already exist
          create_repo: false
          # Set this to true to set a policy on the repository
          set_repo_policy: false
