name: Docker build and push
  # You may pin to the exact commit or the version.
  # uses: kciter/aws-ecr-action@79255b7c5aa03dbf6d7c46cff2bfd049874cd98d
on:
  push:
    branches:
      - 'main'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: kciter/aws-ecr-action@master
      with:
        # The AWS access key id
        access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        # The AWS secret access key
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # AWS Account ID
        account_id: ${{ secrets.AWS_ACCOUNT_ID}}
        # Name of your ECR repository
        repo: weathervane
        # The AWS region
        region: us-east-2
        # Set this to true to create the repository if it does not already exist
        create_repo: false
        # Set this to true to set a policy on the repository
        set_repo_policy: false
